---
title: "Google Cloud & NCAA® ML Competition 2019-Women's"
output: html_notebook
---

## Load the input data
```{r message=FALSE}
library(readr)
library(dplyr)
library(tibble)
library(dfstools)
library(knitr)
RegularSeasonCompactResults <- read_csv(
  "~/DFS/kaggle/WRegularSeasonCompactResults.csv",
  col_types = cols(
    DayNum = col_integer(), 
    LScore = col_integer(), 
    LTeamID = col_integer(),
    NumOT = col_integer(), 
    Season = col_integer(),
    WScore = col_integer(), 
    WTeamID = col_integer())) %>% 
  filter(Season == 2019)
SampleSubmissionStage2 <- read_csv("~/DFS/kaggle/WSampleSubmissionStage2.csv")
Teams <- read_csv(
  "~/DFS/kaggle/WTeams.csv",
  col_types = cols(
    FirstD1Season = col_integer(),
    LastD1Season = col_integer(), 
    TeamID = col_integer()))

```

## Wrangle the data into an mvglmmRank `game.data` input file
```{r}
game_data <- kaggle_game_data(RegularSeasonCompactResults)

```

## Run the slow model (NB.mov)
```{r}
nb_model <- mvglmmRank_model(game_data, method = "NB")

```

## Compute slow rating tibble
```{r}
nb_ratings <- kaggle_ratings(nb_model, Teams)
nb_ratings$TeamID <- as.character(nb_ratings$TeamID)
nb_ratings %>% top_n(16) %>% select(-TeamID) %>% kable(
  row.names = TRUE, digits = 2, format = "pandoc",
  caption = "Women's NCAA® Ratings")

```

## Fill out the submission
```{r}
nb_submission <- SampleSubmissionStage2
for (i in 1:nrow(nb_submission)) {
  nb_submission$Pred[i] <- kaggle_probability(
    nb_model, nb_submission$ID[i])
}
write_csv(
  nb_submission, path = "~/DFS/kaggle/womens_2019_nb_submission.csv")

```

## Session info
```{r}
sessionInfo()
```
