---
title: "Exploring WNBA DFS Data"
output: html_notebook
---

## Load libraries
```{r message=FALSE}
library(tidyverse)
library(DT)
library(dfstools)
```

## Game predictions
```{r}
regular_season_schedule <- dfstools::bdb_wnba_schedule(
  "~/DFS/NBAStuffer_WNBA/2019_WNBA_Regular_Season_Original_Schedule.xlsx"
) %>% dplyr::mutate(
    game_date = strftime(game_start_time, format = "%Y-%m-%d"),
    game_slug = paste0(road_team, " @ ", home_team)
)

this_week <- regular_season_schedule %>% 
  dplyr::filter(
    game_start_time > '2019-08-07',
    game_start_time < '2019-08-14'
  )
season_team_feed <- dfstools::bdb_wnba_team(
  "~/Dropbox/19-wnba-team/08-05-2019-wnba-season-team-feed.xlsx"
)

# rank_model <- dfstools::bdb_wnba_rank_model(season_team_feed)
# augmented_schedule <- dfstools::game_predict(
#   regular_season_schedule, rank_model
# )
# game_score_projections <- augmented_schedule %>%
#   dplyr::semi_join(this_week) %>% 
#   dplyr::select(
#     `Game Start (EDT)` = game_start_time,
#     "Road Team" = road_team,
#     "Home Team" = home_team,
#     "Projected Road Score" = road_team_score_p,
#     "Projected Home Score" = home_team_score_p,
#     "Projected Total" = total_p,
#     "Projected Home Margin of Victory"= home_team_mov_p
#   )
# game_score_projections %>% gt() %>% 
#   gtsave(filename = "game_score_projections.png")

```

## DFS data wrangling
```{r message=FALSE}
season_dfs_feed <- dfstools::bdb_wnba_dfs(
  "~/Dropbox/19-wnba-dfs/08-05-2019-wnba-season-dfs-feed.xlsx"
) %>% dplyr::filter(
  !is.na(fanduel_salary),
  !is.na(draftkings_salary),
  minutes > 0,
  fanduel_points > 0,
  draftkings_points > 0
) %>% dplyr::mutate(
  fanduel_value = 1000 * fanduel_points / fanduel_salary,
  draftkings_value = 1000 * draftkings_points / draftkings_salary
)
fanduel_coefficients <- MASS::rlm(
  fanduel_salary ~ fanduel_points, data = season_dfs_feed)$coefficients
draftkings_coefficients <- MASS::rlm(
  draftkings_salary ~ draftkings_points, data = season_dfs_feed)$coefficients

last_game_played <- season_dfs_feed %>% 
  dplyr::group_by(player_name, own_team, fanduel_position, draftkings_position) %>% 
  dplyr::summarize(games = n(), last_game = max(game_date)) %>% 
  ungroup()

# who's playing where?
road_players <- this_week %>% 
  dplyr::left_join(last_game_played, by = c("road_team" = "own_team")) %>% 
  dplyr::mutate(venue_r_h = "Road", opp_team = home_team)
home_players <- this_week %>% 
  dplyr::left_join(last_game_played, by = c("home_team" = "own_team")) %>%
  dplyr::mutate(venue_r_h = "Home", opp_team = road_team)
to_project <- dplyr::bind_rows(road_players, home_players)

```

## Build models
```{r}
minutes_training <- season_dfs_feed %>% 
  dplyr::select(player_name, opp_team, venue_r_h, minutes)
minutes_glmodel <- stats::glm(
  minutes ~ player_name + opp_team + venue_r_h - 1,
  data = minutes_training, family = gaussian
)

fanduel_training <- season_dfs_feed %>% 
  dplyr::select(player_name, opp_team, venue_r_h, fanduel_points)
fanduel_glmodel <- stats::glm(
  fanduel_points ~ player_name + opp_team + venue_r_h - 1, 
  data = fanduel_training, family = quasipoisson
)

draftkings_training <- season_dfs_feed %>% 
  dplyr::select(player_name, opp_team, venue_r_h, draftkings_points)
draftkings_glmodel <- stats::glm(
  draftkings_points ~ player_name + opp_team + venue_r_h - 1, 
  data = draftkings_training, family = quasipoisson
)

```

## Projections
```{r}
fanduel_projections <- to_project %>% 
  dplyr::mutate(
    projected_minutes = round(predict(
      minutes_glmodel, newdata = to_project, type = "response"), 2),
    projected_fanduel_points = round(predict(
      fanduel_glmodel, newdata = to_project, type = "response"), 2),
    fair_fanduel_salary = round(
      fanduel_coefficients[1] + fanduel_coefficients[2] * projected_fanduel_points, -2),
  ) %>%
  dplyr::select(
    game_date, game_slug, player_name, fanduel_position, opp_team,
    projected_minutes, projected_fanduel_points
  ) %>% 
  dplyr::arrange(game_date, desc(projected_fanduel_points))

draftkings_projections <- to_project %>% 
  dplyr::mutate(
    projected_minutes = round(predict(
      minutes_glmodel, newdata = to_project, type = "response"), 2),
    projected_draftkings_points = round(predict(
      draftkings_glmodel, newdata = to_project, type = "response"), 2),
    fair_draftkings_salary = round(
      draftkings_coefficients[1] + draftkings_coefficients[2] * projected_draftkings_points, -2),
  ) %>%
  dplyr::select(
    game_date, game_slug, player_name, draftkings_position, opp_team,
    projected_minutes, projected_draftkings_points
  ) %>% 
  dplyr::arrange(game_date, desc(projected_draftkings_points))

```

## FanDuel main
```{r}
fanduel_main_rosters <- read_csv("../../FanDuel-WNBA-main.csv") %>% 
  dplyr::select(
    player_name = Nickname, fanduel_position = Position, fanduel_salary = Salary
  )
fanduel_main_slate <- fanduel_projections %>% 
  dplyr::filter(game_date == min(game_date)) %>% 
  dplyr::select(-fanduel_position)
fanduel_main_values <- fanduel_main_rosters %>% 
  dplyr::left_join(fanduel_main_slate) %>% dplyr::select(
    player_name,
    fanduel_position,
    fanduel_salary,
    projected_minutes,
    projected_fanduel_points
  ) %>% dplyr::mutate(
    fanduel_value = 1000 * projected_fanduel_points / fanduel_salary) %>% 
  dplyr::arrange(desc(fanduel_value))
View(fanduel_main_values)

```

## FanDuel single
```{r}
fanduel_single_rosters <- read_csv("../../FanDuel-WNBA-single.csv") %>% 
  dplyr::select(
    player_name = Nickname, fanduel_position = Position, fanduel_salary = Salary
  )
fanduel_single_slate <- fanduel_projections %>% 
  dplyr::filter(game_date == min(game_date)) %>% 
  dplyr::select(-fanduel_position)
fanduel_single_values <- fanduel_single_rosters %>% 
  dplyr::left_join(fanduel_single_slate) %>% dplyr::select(
    player_name,
    fanduel_position,
    fanduel_salary,
    projected_minutes,
    projected_fanduel_points
  ) %>% dplyr::mutate(
    fanduel_value = 1000 * projected_fanduel_points / fanduel_salary) %>% 
  dplyr::arrange(desc(fanduel_value))
View(fanduel_single_values)

```

## DraftKings main
```{r}
draftkings_main_rosters <- read_csv("../../DKSalaries-main.csv") %>% 
  dplyr::select(
    player_name = Name,
    draftkings_position = "Roster Position",
    draftkings_salary = Salary
  )
draftkings_main_slate <- draftkings_projections %>% 
  dplyr::filter(game_date == min(game_date)) %>% 
  dplyr::select(-draftkings_position) 
draftkings_main_values <- draftkings_main_rosters %>% 
  dplyr::left_join(draftkings_main_slate, by = "player_name") %>% dplyr::select(
    player_name,
    draftkings_position,
    draftkings_salary,
    projected_minutes,
    projected_draftkings_points
  ) %>% dplyr::mutate(
    draftkings_value = 1000 * projected_draftkings_points / draftkings_salary) %>% 
  dplyr::arrange(desc(draftkings_value))
View(draftkings_main_values)
```


## DraftKings showdown
```{r}
draftkings_showdown_rosters <- read_csv("../../DKSalaries-showdown.csv") %>% 
  dplyr::select(
    player_name = Name,
    draftkings_position = "Roster Position",
    draftkings_salary = Salary
  )
draftkings_showdown_slate <- draftkings_projections %>% 
  dplyr::filter(game_date == min(game_date)) %>% 
  dplyr::select(-draftkings_position) 
draftkings_showdown_values <- draftkings_showdown_rosters %>% 
  dplyr::left_join(draftkings_showdown_slate, by = "player_name") %>% dplyr::select(
    player_name,
    draftkings_position,
    draftkings_salary,
    projected_minutes,
    projected_draftkings_points
  ) %>% dplyr::mutate(
    draftkings_value = 1000 * projected_draftkings_points / draftkings_salary) %>% 
  dplyr::arrange(desc(draftkings_value))
View(draftkings_showdown_values)
```

