---
title: "Projecting a Season with mvglmmRank"
author: "M. Edward (Ed) Borasky"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{"Projecting a Season with mvglmmRank"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Getting started
1. You'll need an API key for Stattleship. Go to <https://www.patreon.com/stattleship/posts> to sign up.
2. If you haven't already, install `devtools`:`install.packages("devtools")`.
3. Install `tidysportsfeeds`: `devtools::install_github("znmeb/tidysportsfeeds", build_vignettes = TRUE)`.

## Setting the API access token
1. Go to the Stattleship API page <https://api.stattleship.com/> and sign in. Then press the `Copy Access Token` button.
2. Enter the following in the R console:

    ```
    token <- "paste_the_copied_access_token_here"
    library(tidysportsfeeds)
    stattleshipR::set_token(token)
    ```

## Downloading the `games` tibble
1. Choose your league. I'm going to use NBA.
2. Acquire the `games` tibble: `nba_games <- get_games("nba")`.

This will return a tibble of the games in the season, both already played and upcoming. Column `status` will be "upcoming" for upcoming games and "closed" for games that have been played.

## Projecting the rest of the season
1. Run the projections: `nba_result <- project_upcoming_games(nba_games)`. You'll see the iterations for the `mvglmmRank` model. This will take some time, depending on the number of games in the input dataset.

    The result of `project_upcoming_games` is a list of three items:
    
    * projections: a tibble containing the projections,
    * model: the model `mvglmmRank` derived, and
    * model_input: the data from closed games that `mvglmmRank` used.

2. Extract the projections from the result: `nba_projections <- nba_result$projections`.
3. Save as a CSV file: `readr::write_excel_csv(nba_projections, "nba_projections.csv")`.

## The whole thing to copy and paste
```
library(tidysportsfeeds)
stattleshipR::set_token(token)
nba_games <- get_games("nba")
nba_result <- project_upcoming_games(nba_games)
nba_projections <- nba_result$projections
readr::write_excel_csv(nba_projections, "nba_projections.csv"
```

## FAQ

### What do the `projections` columns mean?
* away: The away team name
* home: the home team name
* prob_away_wins: the projected probability that the away team wins
* prob_home_wins: the projected probability that the home team wins
* away_score_proj: the projected score for the away team
* home_score_proj: the projected score for the home team
* home_mov_proj: the projected margin of victory for the home team
* total_proj: the projected total of both teams' scores
* entropy: the projected Shannon entropy for the game
* scheduled_at: the scheduled game start time
* neutral_site: 1 if the game is scheduled at a neutral site
* method: The method used to build the `mvglmmRank` model; the default is "PB1".

The (Shannon) entropy is a measure of information - how much we stand to learn about the teams from the outcome of the game. It's an indicator of the projected closeness of the game. The maximum value, 1.0, indicates that the game is projected to be a tie and we'll learn a lot from the outcome.

A minimum entropy, zero, indicates that the game will be a blowout. There's little we can learn; they might as well just give the game to the favorite and avoid injury risk. ;-) I've never seen a zero; the lowest value of the entropy projections for the upcoming NBA season as of December 26, 2017 is Hawks at Warriors, coming up on 2018-03-23, with a projected entropy of 0.39. The model predicts that there's a 92% probability that the Warriors will win.

### How good are the projections?
They're about as good as you can get given the inputs are just the scores of completed games. They won't be as good as projections that take into account more detailed information from compeleted games.

They won't be as good as a simulation. And they won't be as good as closing odds / point spreads / totals from bookmakers, which account for late-breaking player status and the "wisdom of the crowd". Bottom line: don't risk money on these numbers. I only use them as inputs for projecting player fantasy points.

### Sample output
I've uploaded a sample I ran on December 26, 2017 to <https://docs.google.com/spreadsheets/d/1oy0I_zm92JNrEeMjABXR489LbylT3zI2EwExCPHouMQ/edit?usp=sharing>.

### Where can I find details on `mvglmmRank`?
The package documentation is at @Karl2015, but there's not a lot of the mathematics there. @Broatch2017 gives the math and references earlier papers with more details.

## References
